---
title: "p8105_fp_ds100_yg2625"
author: "Yue Gu"
date: "11/30/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
# Regression Model Analysis

#### Load BRFSS & Injury Data
```{r read_data, message = FALSE}
brfss_data = read_csv("./data/brfss_data.csv") %>% 
  janitor::clean_names()

injury_data = read_csv("./data/NCHS_-_Injury_Mortality__United_States.csv") %>% 
  janitor::clean_names()

```

## Suicide rate model
#### Convert variables into 'factor' to fit a linear model
```{r convert_var}
new_injury = 
  injury_data %>% 
  filter(injury_mechanism == "All Mechanisms",
         injury_intent == "Suicide",
         year  %in%  c(2011, 2012, 2013, 2014, 2015, 2016),
         age_group_years != "All Ages",
         race != "All races",
         sex != "Both sexes") %>%
  mutate(suicide_dr = (deaths / population) * 100000,
         age_group_years = str_replace(age_group_years, "< 15", "<25"),
         age_group_years = str_replace(age_group_years,"15–24", "<25"),
         age_group_years = str_replace(age_group_years,"65–74", "65+"),
         age_group_years = str_replace(age_group_years,"75+", "65")) %>% 
  select(year, sex, age_group_years, race, suicide_dr) %>% 
  mutate(sex = as.factor(ifelse(sex == "Male", 0, 1)),
         race = as.factor(ifelse(race == "Non-Hispanic white", "white", "non-white")),
         age_group_years = as.factor(age_group_years),
         year = as.factor(year))
  
```
#### Construct a regression model using 'suicide death rate' as the outcome of interest with 'sex', 'age group' and 'race' being its predictors
```{r lm}
fit_suicide = lm(suicide_dr ~ sex + race + age_group_years + year, data = new_injury)
summary(fit_suicide)

pairwise.t.test(new_injury$suicide_dr, new_injury$age_group_years, p.adj = 'bonferroni')

fit_suicide %>% aov(.) %>%  TukeyHSD()
```


## Depression model

#### Age model
```{r}

new_brfss_age =
  brfss_data %>% 
  filter(year %in% c(2011, 2012, 2013, 2014, 2015, 2016),
         response == "Yes",
         age_group != "") %>%
  mutate(age_group = str_replace(age_group, "18-24", "<25"),
         age_group = str_replace(age_group, "25-34", "25-44"),
         age_group = str_replace(age_group,"35-44", "25-44"),
         age_group = str_replace(age_group,"45-54", "45-64"),
         age_group = str_replace(age_group,"55-64", "45-64")) %>% 
  select(locationabbr, data_value, age_group) %>% 
  mutate(age_group = as.factor(age_group))

fit_age = lm(data_value ~ locationabbr + age_group, data = new_brfss_age)
summary(fit_age)

fit_age %>% aov(.) %>% TukeyHSD()
```

#### Gender model

```{r}
new_brfss_gender =
  brfss_data %>% 
  filter(year %in% c(2011, 2012, 2013, 2014, 2015, 2016),
         response == "Yes",
         gender != "") %>%
  mutate(total_sp = sample_size/(data_value/100)) %>% 
  select(locationabbr, data_value, gender) %>% 
  mutate(gender = as.factor(ifelse(gender == "Male", 0, 1)))


fit_gender = lm(data_value ~ locationabbr + gender, data = new_brfss_gender)
summary(fit_gender)

fit_gender %>% aov(.) %>% TukeyHSD()
```


#### Race model

```{r}
new_brfss_race =
  brfss_data %>% 
  filter(year %in% c(2011, 2012, 2013, 2014, 2015, 2016),
         response == "Yes",
         race_ethnicity != "") %>%
  mutate(total_sp = sample_size/(data_value/100)) %>% 
  select(locationabbr, data_value, race_ethnicity) %>% 
  mutate(race_ethnicity = as.factor(ifelse(race_ethnicity == "White, non-Hispanic", "white", "nonwhite")))


fit_race = lm(data_value ~ locationabbr + race_ethnicity, data = new_brfss_race)
summary(fit_race)

fit_race %>% aov(.) %>% TukeyHSD()

```



  



