---
title: "p8105_fp_ds100_dataprocess"
author: "Yue Gu, Jianghui Lin, Junyuan Zheng, Jianyou Liu, Zhiqian Fang"
date: "11/5/2018"
output: github_document
---

```{r packages}
library(tidyverse)
library(plotly)
```

```{r data_import}
data_BRFSS = 
  read_csv(file = './data/brfss_data.csv')
data_IM = 
  read_csv(file = './data/NCHS_-_Injury_Mortality__United_States.csv')
```

BRFSS data:
```{r tidy_data_BRFSS}
data_BRFSS_JZ = data_BRFSS %>% 
  janitor::clean_names(.) %>% 
  select(., year, locationabbr, locationdesc, response, sample_size, age_group, gender, race_ethnicity)
```

```{r BRFSS_year_areas}
data_BRFSS_JZ %>% 
  filter(., age_group != 'NA') %>% 
  group_by(., year, locationdesc, response) %>% 
  summarize(., sum_sample_size = sum(sample_size)) %>% 
  spread(., key = response, value = sum_sample_size) %>% 
  mutate(., prevalence = (Yes / (Yes + No)),
    ci_low = prevalence - qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No)),
    ci_high = prevalence + qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No))) %>% 
  ggplot(., aes(x = year, y = prevalence, color = locationdesc)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.05, alpha = 0.5) +
  theme(legend.position = 'right', legend.text = element_text(size=4), legend.box = 'vertical',
        legend.key.size = unit(0.1, 'cm')) +
  ggtitle('Depression Prevalence from 2011-2016 by 54 Areas in US')
```

```{r BRFSS_year_age}
data_BRFSS_JZ %>%
  mutate(., age_group = str_replace(age_group, '25-34', '25-44'),
            age_group = str_replace(age_group, '35-44', '25-44'),
            age_group = str_replace(age_group, '45-54', '45-64'),
            age_group = str_replace(age_group, '55-64', '45-64')) %>% 
  filter(., age_group != 'NA') %>% 
  group_by(., year, response, age_group) %>% 
  summarize(., sum_sample_size = sum(sample_size)) %>% 
  spread(., key = response, value = sum_sample_size) %>% 
  mutate(., prevalence = (Yes / (Yes + No)),
    ci_low = prevalence - qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No)),
    ci_high = prevalence + qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No))) %>% 
  ggplot(., aes(x = year, y = prevalence, color = age_group)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.1, alpha = 0.5) + 
  theme(legend.position = 'right', legend.text = element_text(size=6), legend.box = 'vertical',
        legend.key.size = unit(1, 'cm')) +
  ggtitle('Depression Prevalence from 2011-2016 by Age Groups')
```

```{r BRFSS_year_gender}
data_BRFSS_JZ %>% 
  filter(., gender != 'NA') %>% 
  group_by(., year, gender, response) %>% 
  summarize(., sum_sample_size = sum(sample_size)) %>% 
  spread(., key = response, value = sum_sample_size) %>% 
  mutate(., prevalence = (Yes / (Yes + No)),
    ci_low = prevalence - qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No)),
    ci_high = prevalence + qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No))) %>% 
  ggplot(., aes(x = year, y = prevalence, color = gender)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.5, alpha = 1) +
  theme(legend.position = 'right', legend.text = element_text(size=6), legend.box = 'vertical',
        legend.key.size = unit(1, 'cm')) +
  ggtitle('Depression Prevalence from 2011-2016 by Genders')
```

```{r BRFSS_year_race}
data_BRFSS_JZ %>% 
  mutate(., race_ethnicity = str_replace(race_ethnicity, 'American Indian or Alaskan Native, non-Hispanic', 'Other'),
            race_ethnicity = str_replace(race_ethnicity, 'Asian, non-Hispanic', 'Other'),
            race_ethnicity = str_replace(race_ethnicity, 'Multiracial, non-Hispanic', 'Other'),
            race_ethnicity = str_replace(race_ethnicity, 'Native Hawaiian or other Pacific Islander, non-Hispanic', 'Other'),
            race_ethnicity = str_replace(race_ethnicity, 'Other, non-Hispanic', 'Other')) %>%  
  filter(., race_ethnicity != 'NA') %>% 
  group_by(., year, response, race_ethnicity) %>% 
  summarize(., sum_sample_size = sum(sample_size)) %>% 
  spread(., key = response, value = sum_sample_size) %>% 
  mutate(., prevalence = (Yes / (Yes + No)),
    ci_low = prevalence - qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No)),
    ci_high = prevalence + qnorm(.975) * sqrt(prevalence * (1 - prevalence) / (Yes + No))) %>%
  mutate(., race_ethnicity = forcats::fct_relevel(race_ethnicity,
                     c('Hispanic', 'Black, non-Hispanic', 'White, non-Hispanic', 'Other'))) %>%
  ggplot(., aes(x = year, y = prevalence, color = race_ethnicity)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.1, alpha = 0.8) + 
  theme(legend.position = 'right', legend.text = element_text(size=6), legend.box = 'vertical',
        legend.key.size = unit(1, 'cm')) +
  ggtitle('Depression Prevalence from 2011-2016 by Race')
  
```

IM data:
```{r tidy_data_IM}
data_IM_JZ = data_IM %>% 
  janitor::clean_names(.) %>% 
  filter(., injury_intent == 'Suicide',
    year == 2011 | year == 2012 | year == 2013 | year == 2014 | year == 2015 | year == 2016,
    sex != 'Both sexes',
    age_group_years != 'All Ages',
    race != 'All races',
    injury_mechanism == 'All Mechanisms')
```

```{r IM_year_age}
data_IM_JZ %>% 
  mutate(., age_group_years = str_replace(age_group_years, '< 15', '< 25'),
            age_group_years = str_replace(age_group_years, '15–24', '< 25'),
            age_group_years = str_replace(age_group_years, '65–74', '65+'),
            age_group_years = str_replace(age_group_years, '75+', '65')) %>% 
  group_by(., year, age_group_years) %>% 
  summarize(., deaths = sum(deaths), population = sum(population)) %>% 
  mutate(., death_rate = (deaths / population),
    ci_low = death_rate - qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population),
    ci_high = death_rate + qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population)) %>%
  mutate(., age = forcats::fct_relevel(age_group_years, c('< 25', '25–44', '45–64', '65+'))) %>% 
  ggplot(., aes(x = year, y = death_rate, color = age_group_years)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.1, alpha = 0.8) + 
  theme(legend.position = 'right', legend.text = element_text(size=6), legend.box = 'vertical',
        legend.key.size = unit(1, 'cm')) +
  ggtitle('Suicide Death Rate from 2011-2016 by Age')
```


```{r IM_year_gender}
data_IM_JZ %>% 
  group_by(., year, sex) %>% 
  summarize(., sum_deaths = sum(deaths), population = sum(population)) %>% 
  mutate(., death_rate = (sum_deaths / population),
    ci_low = death_rate - qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population),
    ci_high = death_rate + qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population)) %>% 
  ggplot(., aes(x = year, y = death_rate, color = sex)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.5, alpha = 0.8) + 
  theme(legend.position = 'right', legend.text = element_text(size=6), legend.box = 'vertical',
        legend.key.size = unit(1, 'cm')) +
  ggtitle('Suicide Death Rate from 2011-2016 by Age')
```

```{r IM_year_race_DB}
data_IM_JZ %>% 
  group_by(., year, race) %>%
  summarize(., sum_deaths = sum(deaths), population = sum(population)) %>% 
  mutate(., death_rate = (sum_deaths / population),
    ci_low = death_rate - qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population),
    ci_high = death_rate + qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population)) %>% 
  ggplot(., aes(x = year, y = death_rate, color = race)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = ci_high, ymin = ci_low), width = 0.5, alpha = 0.5) + 
  theme(legend.position = 'right', legend.text = element_text(size=6), legend.box = 'vertical',
        legend.key.size = unit(1, 'cm')) +
  ggtitle('Suicide Death Rate from 2011-2016 by Age')
```

test:
```{r IM_year_race}
data_IM_JZ %>% 
  group_by(., year, race) %>%
  summarize(., sum_deaths = sum(deaths), population = sum(population)) %>% 
  mutate(., death_rate = (sum_deaths / population),
    ci_low = death_rate - qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population),
    ci_high = death_rate + qnorm(.975) * sqrt(death_rate * (1 - death_rate) / population)) %>%
  plot_ly(y = ~death_rate, x = ~year, color = ~race, type = 'scatter', mode = 'line+marker',
          error_y = ~list(array = c(ci_high - death_rate)))
```



